Repository Maagan-Michael/invitease, pull requests merged in 2021-12, with the labels that each got.

#27 Went on a Docker diet
  Dockerfile
Labels: enhancement, security

#38 Adding invitations query
  src/database/__init__.py
  src/database/invitation_repository.py
  src/database/repository_base.py
Labels: enhancement

#39 Defined sh files to have LF line endings.
  .gitattributes
Labels: bug

#41 Træfik implementation and small usability fixes
  db_init/baseline.sql
  docker-compose.yml
  entry_point.sh
  src/database/__init__.py
  src/routers/inviter_router.py
  src/utilities.py
Labels: enhancement

#43 Implemented foreign key support
  src/authentication.py
  src/database/__init__.py
  src/database/eventlog_repository.py
  src/database/models.py
  src/database/repository_base.py
  src/utilities.py
Labels: enhancement

#48 Modified: 15.0.2 -> 15.1.0
  docker-compose.yml
Labels: enhancement

#49 Fix KeyCloak integration.
  docker-compose.yml
  src/core/__init__.py
  src/core/authentication.py
  src/core/utilities.py
  src/main.py
  src/routers/admin_router.py
Labels: enhancement

#53 Added PgAdmin, preconfigured servers.json and restart policy
  db_init/servers.json
  docker-compose.yml
Labels: enhancement

#58 Implemented scripts for seeding keycloak.
  docker-compose.yml
  init/key-cloak-seed.sh
  init/linux.sh
  init/windows.bat
Labels: enhancement
